class CfgPatches {class tsp_tier1_sawfix {requiredAddons[] = {"Tier1_Weapons_cfg"}; units[] = {}; skipWhenMissingDependencies = 1;};};
class cfgweapons {
	class Rifle;
	class Rifle_Base_F: Rifle {};
	class Tier1_SAW_Base: Rifle_Base_F {};
	class Tier1_MK46_Mod0: Tier1_SAW_Base {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawfix.rtm"};};
	class Tier1_MK46_Mod0_grip: Tier1_MK46_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod0_grip2: Tier1_MK46_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK46_Mod0_grip3: Tier1_MK46_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod0_Desert: Tier1_MK46_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawfix.rtm"};};
	class Tier1_MK46_Mod0_Desert_grip: Tier1_MK46_Mod0_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod0_Desert_grip2: Tier1_MK46_Mod0_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK46_Mod0_Desert_grip3: Tier1_MK46_Mod0_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod0_Para: Tier1_MK46_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawfix.rtm"};};
	class Tier1_MK46_Mod0_Para_grip: Tier1_MK46_Mod0_Para {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod0_Para_grip2: Tier1_MK46_Mod0_Para {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK46_Mod0_Para_grip3: Tier1_MK46_Mod0_Para {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod0_Para_Desert: Tier1_MK46_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawfix.rtm"};};
	class Tier1_MK46_Mod0_Para_Desert_grip: Tier1_MK46_Mod0_Para_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod0_Para_Desert_grip2: Tier1_MK46_Mod0_Para_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK46_Mod0_Para_Desert_grip3: Tier1_MK46_Mod0_Para_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod1: Tier1_MK46_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsavitfix.rtm"};};
	class Tier1_MK46_Mod1_grip: Tier1_MK46_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod1_grip2: Tier1_MK46_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK46_Mod1_grip3: Tier1_MK46_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod1_Desert: Tier1_MK46_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsavitfix.rtm"};};
	class Tier1_MK46_Mod1_Desert_grip: Tier1_MK46_Mod1_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod1_Desert_grip2: Tier1_MK46_Mod1_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK46_Mod1_Desert_grip3: Tier1_MK46_Mod1_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod1_Savit: Tier1_MK46_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsavitfix.rtm"};};
	class Tier1_MK46_Mod1_Savit_grip: Tier1_MK46_Mod1_Savit {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod1_Savit_grip2: Tier1_MK46_Mod1_Savit {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK46_Mod1_Savit_grip3: Tier1_MK46_Mod1_Savit {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod1_Savit_Desert: Tier1_MK46_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsavitfix.rtm"};};
	class Tier1_MK46_Mod1_Savit_Desert_grip: Tier1_MK46_Mod1_Savit_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK46_Mod1_Savit_Desert_grip2: Tier1_MK46_Mod1_Savit_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK46_Mod1_Savit_Desert_grip3: Tier1_MK46_Mod1_Savit_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod0: Tier1_SAW_Base {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawfix.rtm"};};
	class Tier1_MK48_Mod0_grip: Tier1_MK48_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod0_grip2: Tier1_MK48_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK48_Mod0_grip3: Tier1_MK48_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod0_Desert: Tier1_MK48_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawfix.rtm"};};
	class Tier1_MK48_Mod0_Desert_grip: Tier1_MK48_Mod0_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod0_Desert_grip2: Tier1_MK48_Mod0_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK48_Mod0_Desert_grip3: Tier1_MK48_Mod0_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod0_Para: Tier1_MK48_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawfix.rtm"};};
	class Tier1_MK48_Mod0_Para_grip: Tier1_MK48_Mod0_Para {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod0_Para_grip2: Tier1_MK48_Mod0_Para {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK48_Mod0_Para_grip3: Tier1_MK48_Mod0_Para {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod0_Para_Desert: Tier1_MK48_Mod0_Para {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawfix.rtm"};};
	class Tier1_MK48_Mod0_Para_Desert_grip: Tier1_MK48_Mod0_Para_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod0_Para_Desert_grip2: Tier1_MK48_Mod0_Para_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK48_Mod0_Para_Desert_grip3: Tier1_MK48_Mod0_Para_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod1: Tier1_MK48_Mod0 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsavitfix.rtm"};};
	class Tier1_MK48_Mod1_grip: Tier1_MK48_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod1_grip2: Tier1_MK48_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK48_Mod1_grip3: Tier1_MK48_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod1_Desert: Tier1_MK48_Mod1 {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsavitfix.rtm"};};
	class Tier1_MK48_Mod1_Desert_grip: Tier1_MK48_Mod1_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
	class Tier1_MK48_Mod1_Desert_grip2: Tier1_MK48_Mod1_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawsgripfix.rtm"};};
	class Tier1_MK48_Mod1_Desert_grip3: Tier1_MK48_Mod1_Desert {handAnim[] = {"OFP2_ManSkeleton", "\tsp_tier1_sawfix\Anim\sawvfgfix.rtm"};};
};